### PR TITLE
Output less text when building

### PR DESCRIPTION
**Pull request by jyn514**
This is vaguely in the style of the Linux kernel's output, but doesn't try to match it exactly.

- Don't print all clang flags each time a C file is compiled.
  Previously, the makefile would repeat all the flags to clang for each file:
  ```
  "clang" -O2 -DNDEBUG --target=wasm32-wasi -fno-trapping-math -Wall -Wextra -Werror -Wno-null-pointer-arithmetic -Wno-unused-parameter -Wno-sign-compare -Wno-unused-variable -Wno-unused-function -Wno-ignored-attributes -Wno-missing-braces -Wno-ignored-pragmas -mthread-model single --sysroot="/home/jnelson/src/wasi-libc/sysroot" -I/home/jnelson/src/wasi-libc/libc-bottom-half/headers/private -I/home/jnelson/src/wasi-libc/libc-bottom-half/cloudlibc/src/include -I/home/jnelson/src/wasi-libc/libc-bottom-half/cloudlibc/src -MD -MP -o /home/jnelson/src/wasi-libc/build/libc-bottom-half/cloudlibc/src/libc/unistd/readlinkat.o -c /home/jnelson/src/wasi-libc/libc-bottom-half/cloudlibc/src/libc/unistd/readlinkat.c
  ```

  This changes it to only print the name of the file being compiled.
  It also slightly refactors the C compiler invocations to avoid repeating them three times.

- Don't print all object files being assembled
  There can be several hundred object files assembled at once:
  ```
  llvm-ar crs /home/jnelson/src/wasi-libc/sysroot/lib/wasm32-wasi/libc.a /home/jnelson/src/wasi-libc/build/dlmalloc/src/dlmalloc.o /home/jnelson/src/wasi-libc/build/libc-bottom-half/cloudlibc/src/libc/poll/poll.o /home/jnelson/src/wasi-libc/build/libc-bottom-half/cloudlibc/src/libc/errno/errno.o /home/jnelson/src/wasi-libc/build/libc-bottom-half/cloudlibc/src/libc/sched/sched_yield.o /home/jnelson/src/wasi-libc/build/libc-bottom-half/cloudlibc/src/libc/fcntl/posix_fadvise.o /home/jnelson/src/wasi-libc/build/libc-bottom-half/cloudlibc/src/libc/fcntl/posix_fallocate.o /home/jnelson/src/wasi-libc/build/libc-bottom-half/cloudlibc/src/libc/fcntl/fcntl.o /home/jnelson/src/wasi-libc/build/libc-bottom-half/cloudlibc/src/libc/fcntl/openat.o /home/jnelson/src/wasi-libc/build/libc-bottom-half/cloudlibc/src/libc/time/CLOCK_THREAD_CPUTIME_ID.o /home/jnelson/src/wasi-libc/build/libc-bottom-half/cloudlibc/src/libc/time/clock_getres.o /home/jnelson/src/wasi-libc/build/libc-bottom-half/cloudlibc/src/libc/time/nanosleep.o /home/jnelson/src/wasi-libc/build/libc-bottom-half/cloudlibc/src/libc/time/clock_gettime.o /home/jnelson/src/wasi-libc/build/libc-bottom-half/cloudlibc/src/libc/time/CLOCK_MONOTONIC.o /home/jnelson/src/wasi-libc/build/libc-bottom-half/cloudlibc/src/libc/time/clock_nanosleep.o /home/jnelson/src/wasi-libc/build/libc-bottom-half/cloudlibc/src/libc/time/CLOCK_PROCESS_CPUTIME_ID.o /home/jnelson/src/wasi-libc/build/libc-bottom-half/cloudlibc/src/libc/time/CLOCK_REALTIME.o /home/jnelson/src/wasi-libc/build/libc-bottom-half/cloudlibc/src/libc/time/time.o /home/jnelson/src/wasi-libc/build/libc-bottom-half/cloudlibc/src/libc/stdlib/_Exit.o /home/jnelson/src/wasi-libc/build/libc-bottom-half/cloudlibc/src/libc/stdio/renameat.o /home/jnelson/src/wasi-libc/build/libc-bottom-half/cloudlibc/src/libc/unistd/write.o /home/jnelson/src/wasi-libc/build/libc-bottom-half/cloudlibc/src/libc/unistd/linkat.o /home/jnelson/src/wasi-libc/build/libc-bottom-half/cloudlibc/src/libc/unistd/readlinkat.o /home/jnelson/src/wasi-libc/build/libc-bottom-half/cloudlibc/src/libc/unistd/symlinkat.o /home/jnelson/src/wasi-libc/build/libc-bottom-half/cloudlibc/src/libc/unistd/ftruncate.o /home/jnelson/src/wasi-libc/build/libc-bottom-half/cloudlibc/src/libc/unistd/unlinkat.o /home/jnelson/src/wasi-libc/build/libc-bottom-half/cloudlibc/src/libc/unistd/pwrite.o /home/jnelson/src/wasi-libc/build/libc-bottom-half/cloudlibc/src/libc/unistd/usleep.o /home/jnelson/src/wasi-libc/build/libc-bottom-half/cloudlibc/src/libc/unistd/lseek.o /home/jnelson/src/wasi-libc/build/libc-bottom-half/cloudlibc/src/libc/unistd/close.o /home/jnelson/src/wasi-libc/build/libc-bottom-half/cloudlibc/src/libc/unistd/read.o /home/jnelson/src/wasi-libc/build/libc-bottom-half/cloudlibc/src/libc/unistd/fdatasync.o /home/jnelson/src/wasi-libc/build/libc-bottom-half/cloudlibc/src/libc/unistd/pread.o /home/jnelson/src/wasi-libc/build/libc-bottom-half/cloudlibc/src/libc/unistd/sleep.o /home/jnelson/src/wasi-libc/build/libc-bottom-half/cloudlibc/src/libc/unistd/fsync.o /home/jnelson/src/wasi-libc/build/libc-bottom-half/cloudlibc/src/libc/unistd/faccessat.o /home/jnelson/src/wasi-libc/build/libc-bottom-half/cloudlibc/src/libc/dirent/readdir.o /home/jnelson/src/wasi-libc/build/libc-bottom-half/cloudlibc/src/libc/dirent/rewinddir.o /home/jnelson/src/wasi-libc/build/libc-bottom-half/cloudlibc/src/libc/dirent/opendirat.o /home/jnelson/src/wasi-libc/build/libc-bottom-half/cloudlibc/src/libc/dirent/fdclosedir.o /home/jnelson/src/wasi-libc/build/libc-bottom-half/cloudlibc/src/libc/dirent/fdopendir.o /home/jnelson/src/wasi-libc/build/libc-bottom-half/cloudlibc/src/libc/dirent/dirfd.o /home/jnelson/src/wasi-libc/build/libc-bottom-half/cloudlibc/src/libc/dirent/seekdir.o /home/jnelson/src/wasi-libc/build/libc-bottom-half/cloudlibc/src/libc/dirent/telldir.o /home/jnelson/src/wasi-libc/build/libc-bottom-half/cloudlibc/src/libc/dirent/scandirat.o /home/jnelson/src/wasi-libc/build/libc-bottom-half/cloudlibc/src/libc/dirent/closedir.o /home/jnelson/src/wasi-libc/build/libc-bottom-half/cloudlibc/src/libc/sys/stat/fstat.o /home/jnelson/src/wasi-libc/build/libc-bottom-half/cloudlibc/src/libc/sys/stat/utimensat.o /home/jnelson/src/wasi-libc/build/libc-bottom-half/cloudlibc/src/libc/sys/stat/fstatat.o /home/jnelson/src/wasi-libc/build/libc-bottom-half/cloudlibc/src/libc/sys/stat/futimens.o /home/jnelson/src/wasi-libc/build/libc-bottom-half/cloudlibc/src/libc/sys/stat/mkdirat.o /home/jnelson/src/wasi-libc/build/libc-bottom-half/cloudlibc/src/libc/sys/uio/readv.o /home/jnelson/src/wasi-libc/build/libc-bottom-half/cloudlibc/src/libc/sys/uio/writev.o /home/jnelson/src/wasi-libc/build/libc-bottom-half/cloudlibc/src/libc/sys/uio/pwritev.o /home/jnelson/src/wasi-libc/build/libc-bottom-half/cloudlibc/src/libc/sys/uio/preadv.o /home/jnelson/src/wasi-libc/build/libc-bottom-half/cloudlibc/src/libc/sys/ioctl/ioctl.o /home/jnelson/src/wasi-libc/build/libc-bottom-half/cloudlibc/src/libc/sys/time/gettimeofday.o /home/jnelson/src/wasi-libc/build/libc-bottom-half/cloudlibc/src/libc/sys/select/pselect.o /home/jnelson/src/wasi-libc/build/libc-bottom-half/cloudlibc/src/libc/sys/select/select.o /home/jnelson/src/wasi-libc/build/libc-bottom-half/cloudlibc/src/libc/sys/socket/getsockopt.o /home/jnelson/src/wasi-libc/build/libc-bottom-half/cloudlibc/src/libc/sys/socket/recv.o /home/jnelson/src/wasi-libc/build/libc-bottom-half/cloudlibc/src/libc/sys/socket/shutdown.o /home/jnelson/src/wasi-libc/build/libc-bottom-half/cloudlibc/src/libc/sys/socket/send.o /home/jnelson/src/wasi-libc/build/libc-bottom-half/sources/errno.o /home/jnelson/src/wasi-libc/build/libc-bottom-half/sources/__main_void.o /home/jnelson/src/wasi-libc/build/libc-bottom-half/sources/getentropy.o /home/jnelson/src/wasi-libc/build/libc-bottom-half/sources/complex-builtins.o /home/jnelson/src/wasi-libc/build/libc-bottom-half/sources/isatty.o /home/jnelson/src/wasi-libc/build/libc-bottom-half/sources/abort.o /home/jnelson/src/wasi-libc/build/libc-bottom-half/sources/truncate.o /home/jnelson/src/wasi-libc/build/libc-bottom-half/sources/sbrk.o /home/jnelson/src/wasi-libc/build/libc-bottom-half/sources/math/math-builtins.o /home/jnelson/src/wasi-libc/build/libc-bottom-half/sources/math/fmin-fmax.o /home/jnelson/src/wasi-libc/build/libc-bottom-half/sources/__wasilibc_fd_renumber.o /home/jnelson/src/wasi-libc/build/libc-bottom-half/sources/__wasilibc_tell.o /home/jnelson/src/wasi-libc/build/libc-bottom-half/sources/__main_argc_argv.o /home/jnelson/src/wasi-libc/build/libc-bottom-half/sources/__wasilibc_environ.o /home/jnelson/src/wasi-libc/build/libc-bottom-half/sources/__original_main.o /home/jnelson/src/wasi-libc/build/libc-bottom-half/sources/environ.o /home/jnelson/src/wasi-libc/build/libc-bottom-half/sources/posix.o /home/jnelson/src/wasi-libc/build/libc-bottom-half/sources/at_fdcwd.o /home/jnelson/src/wasi-libc/build/libc-bottom-half/sources/preopens.o /home/jnelson/src/wasi-libc/build/libc-bottom-half/sources/reallocarray.o /home/jnelson/src/wasi-libc/build/libc-bottom-half/sources/__wasilibc_rmdirat.o /home/jnelson/src/wasi-libc/build/libc-bottom-half/sources/__wasilibc_real.o /home/jnelson/src/wasi-libc/build/libc-bottom-half/sources/__wasilibc_unlinkat.o /home/jnelson/src/wasi-libc/build/libc-bottom-half/sources/getcwd.o /home/jnelson/src/wasi-libc/build/libc-bottom-half/sources/__wasilibc_initialize_environ.o /home/jnelson/src/wasi-libc/build/libc-bottom-half/sources/chdir.o /home/jnelson/src/wasi-libc/build/libc-top-half/musl/src/misc/a64l.o /home/jnelson/src/wasi-libc/build/libc-top-half/musl/src/misc/basename.o /home/jnelson/src/wasi-libc/build/libc-top-half/musl/src/misc/dirname.o /home/jnelson/src/wasi-libc/build/libc-top-half/musl/src/misc/ffs.o /home/jnelson/src/wasi-libc/build/libc-top-half/musl/src/misc/ffsl.o /home/jnelson/src/wasi-libc/build/libc-top-half/musl/src/misc/ffsll.o /home/jnelson/src/wasi-libc/build/libc-top-half/musl/src/misc/fmtmsg.o /home/jnelson/src/wasi-libc/build/libc-top-half/musl/src/misc/getdomainname.o /home/jnelson/src/wasi-libc/build/libc-top-half/musl/src/misc/gethostid.o /home/jnelson/src/wasi-libc/build/libc-top-half/musl/src/misc/getopt.o /home/jnelson/src/wasi-libc/build/libc-top-half/musl/src/misc/getopt_long.o /home/jnelson/src/wasi-libc/build/libc-top-half/musl/src/misc/getsubopt.o /home/jnelson/src/wasi-libc/build/libc-top-half/musl/src/misc/uname.o /home/jnelson/src/wasi-libc/build/libc-top-half/musl/src/misc/nftw.o /home/jnelson/src/wasi-libc/build/libc-top-half/musl/src/errno/strerror.o /home/jnelson/src/wasi-libc/build/libc-top-half/musl/src/network/htonl.o /home/jnelson/src/wasi-libc/build/libc-top-half/musl/src/network/htons.o /home/jnelson/src/wasi-libc/build/libc-top-half/musl/src/network/ntohl.o /home/jnelson/src/wasi-libc/build/libc-top-half/musl/src/network/ntohs.o /home/jnelson/src/wasi-libc/build/libc-top-half/musl/src/network/inet_ntop.o /home/jnelson/src/wasi-libc/build/libc-top-half/musl/src/network/inet_pton.o /home/jnelson/src/wasi-libc/build/libc-top-half/musl/src/network/inet_aton.o /home/jnelson/src/wasi-libc/build/libc-top-half/musl/src/network/in6addr_any.o /home/jnelson/src/wasi-libc/build/libc-top-half/musl/src/network/in6addr_loopback.o /home/jnelson/src/wasi-libc/build/libc-top-half/musl/src/fenv/fenv.o /home/jnelson/src/wasi-libc/build/libc-top-half/musl/src/fenv/fesetround.o /home/jnelson/src/wasi-libc/build/libc-top-half/musl/src/fenv/feupdateenv.o /home/jnelson/src/wasi-libc/build/libc-top-half/musl/src/fenv/fesetexceptflag.o /home/jnelson/src/wasi-libc/build/libc-top-half/musl/src/fenv/fegetexceptflag.o /home/jnelson/src/wasi-libc/build/libc-top-half/musl/src/fenv/feholdexcept.o /home/jnelson/src/wasi-libc/build/libc-top-half/musl/src/exit/exit.o /home/jnelson/src/wasi-libc/build/libc-top-half/musl/src/exit/atexit.o /home/jnelson/src/wasi-libc/build/libc-top-half/musl/src/exit/assert.o /home/jnelson/src/wasi-libc/build/libc-top-half/musl/src/exit/quick_exit.o /home/jnelson/src/wasi-libc/build/libc-top-half/musl/src/exit/at_quick_exit.o /home/jnelson/src/wasi-libc/build/libc-top-half/musl/src/time/strftime.o /home/jnelson/src/wasi-libc/build/libc-top-half/musl/src/time/asctime.o /home/jnelson/src/wasi-libc/build/libc-top-half/musl/src/time/asctime_r.o /home/jnelson/src/wasi-libc/build/libc-top-half/musl/src/time/ctime.o /home/jnelson/src/wasi-libc/build/libc-top-half/musl/src/time/ctime_r.o /home/jnelson/src/wasi-libc/build/libc-top-half/musl/src/time/wcsftime.o /home/jnelson/src/wasi-libc/build/libc-top-half/musl/src/time/strptime.o /home/jnelson/src/wasi-libc/build/libc-top-half/musl/src/time/difftime.o /home/jnelson/src/wasi-libc/build/libc-top-half/musl/src/time/timegm.o /home/jnelson/src/wasi-libc/build/libc-top-half/musl/src/time/ftime.o /home/jnelson/src/wasi-libc/build/libc-top-half/musl/src/time/gmtime.o /home/jnelson/src/wasi-libc/build/libc-top-half/musl/src/time/gmtime_r.o /home/jnelson/src/wasi-libc/build/libc-top-half/musl/src/time/timespec_get.o /home/jnelson/src/wasi-libc/build/libc-top-half/musl/src/time/getdate.o /home/jnelson/src/wasi-libc/build/libc-top-half/musl/src/time/localtime.o /home/jnelson/src/wasi-libc/build/libc-top-half/musl/src/time/localtime_r.o /home/jnelson/src/wasi-libc/build/libc-top-half/musl/src/time/mktime.o /home/jnelson/src/wasi-libc/build/libc-top-half/musl/src/time/__tm_to_secs.o /home/jnelson/src/wasi-libc/build/libc-top-half/musl/src/time/__month_to_secs.o /home/jnelson/src/wasi-libc/build/libc-top-half/musl/src/time/__secs_to_tm.o /home/jnelson/src/wasi-libc/build/libc-top-half/musl/src/time/__year_to_secs.o /home/jnelson/src/wasi-libc/build/libc-top-half/musl/src/time/__tz.o /home/jnelson/src/wasi-libc/build/libc-top-half/musl/src/fcntl/creat.o /home/jnelson/src/wasi-libc/build/libc-top-half/musl/src/dirent/alphasort.o /home/jnelson/src/wasi-libc/build/libc-top-half/musl/src/dirent/versionsort.o /home/jnelson/src/wasi-libc/build/libc-top-half/musl/src/env/clearenv.o /home/jnelson/src/wasi-libc/build/libc-top-half/musl/src/env/getenv.o /home/jnelson/src/wasi-libc/build/libc-top-half/musl/src/env/putenv.o /home/jnelson/src/wasi-libc/build/libc-top-half/musl/src/env/setenv.o /home/jnelson/src/wasi-libc/build/libc-top-half/musl/src/env/unsetenv.o /home/jnelson/src/wasi-libc/build/libc-top-half/musl/src/unistd/posix_close.o /home/jnelson/src/wasi-libc/build/libc-top-half/musl/src/internal/floatscan.o /home/jnelson/src/wasi-libc/build/libc-top-half/musl/src/internal/intscan.o /home/jnelson/src/wasi-libc/build/libc-top-half/musl/src/internal/shgetc.o /home/jnelson/src/wasi-libc/build/libc-top-half/musl/src/internal/defsysinfo.o /home/jnelson/src/wasi-libc/build/libc-top-half/musl/src/internal/libc.o /home/jnelson/src/wasi-libc/build/libc-top-half/musl/src/stdio/fseek.o /home/jnelson/src/wasi-libc/build/libc-top-half/musl/src/stdio/getline.o /home/jnelson/src/wasi-libc/build/libc-top-half/musl/src/stdio/fputws.o /home/jnelson/src/wasi-libc/build/libc-top-half/musl/src/stdio/fputwc.o /home/jnelson/src/wasi-libc/build/libc-top-half/musl/src/stdio/fwrite.o /home/jnelson/src/wasi-libc/build/libc-top-half/musl/src/stdio/open_memstream.o /home/jnelson/src/wasi-libc/build/libc-top-half/musl/src/stdio/clearerr.o /home/jnelson/src/wasi-libc/build/libc-top-half/musl/src/stdio/fclose.o /home/jnelson/src/wasi-libc/build/libc-top-half/musl/src/stdio/getwc.o /home/jnelson/src/wasi-libc/build/libc-top-half/musl/src/stdio/stdin.o /home/jnelson/src/wasi-libc/build/libc-top-half/musl/src/stdio/ftell.o /home/jnelson/src/wasi-libc/build/libc-top-half/musl/src/stdio/__fmodeflags.o /home/jnelson/src/wasi-libc/build/libc-top-half/musl/src/stdio/vdprintf.o /home/jnelson/src/wasi-libc/build/libc-top-half/musl/src/stdio/fgetws.o /home/jnelson/src/wasi-libc/build/libc-top-half/musl/src/stdio/vwprintf.o /home/jnelson/src/wasi-libc/build/libc-top-half/musl/src/stdio/dprintf.o /home/jnelson/src/wasi-libc/build/libc-top-half/musl/src/stdio/__stdio_seek.o /home/jnelson/src/wasi-libc/build/libc-top-half/musl/src/stdio/vsscanf.o /home/jnelson/src/wasi-libc/build/libc-top-half/musl/src/stdio/fgetwc.o /home/jnelson/src/wasi-libc/build/libc-top-half/musl/src/stdio/getc.o /home/jnelson/src/wasi-libc/build/libc-top-half/musl/src/stdio/setbuffer.o /home/jnelson/src/wasi-libc/build/libc-top-half/musl/src/stdio/ext2.o /home/jnelson/src/wasi-libc/build/libc-top-half/musl/src/stdio/fputs.o /home/jnelson/src/wasi-libc/build/libc-top-half/musl/src/stdio/__fdopen.o /home/jnelson/src/wasi-libc/build/libc-top-half/musl/src/stdio/__stdio_write.o /home/jnelson/src/wasi-libc/build/libc-top-half/musl/src/stdio/feof.o /home/jnelson/src/wasi-libc/build/libc-top-half/musl/src/stdio/vswscanf.o /home/jnelson/src/wasi-libc/build/libc-top-half/musl/src/stdio/ungetc.o /home/jnelson/src/wasi-libc/build/libc-top-half/musl/src/stdio/__fclose_ca.o /home/jnelson/src/wasi-libc/build/libc-top-half/musl/src/stdio/ofl_add.o /home/jnelson/src/wasi-libc/build/libc-top-half/musl/src/stdio/stderr.o /home/jnelson/src/wasi-libc/build/libc-top-half/musl/src/stdio/fgets.o /home/jnelson/src/wasi-libc/build/libc-top-half/musl/src/stdio/ungetwc.o /home/jnelson/src/wasi-libc/build/libc-top-half/musl/src/stdio/scanf.o /home/jnelson/src/wasi-libc/build/libc-top-half/musl/src/stdio/freopen.o /home/jnelson/src/wasi-libc/build/libc-top-half/musl/src/stdio/__uflow.o /home/jnelson/src/wasi-libc/build/libc-top-half/musl/src/stdio/vswprintf.o /home/jnelson/src/wasi-libc/build/libc-top-half/musl/src/stdio/putchar.o /home/jnelson/src/wasi-libc/build/libc-top-half/musl/src/stdio/vsprintf.o /home/jnelson/src/wasi-libc/build/libc-top-half/musl/src/stdio/putchar_unlocked.o
  ```
  After this commit, make will only print the name of the output, not all the inputs.
  ```
  AR crs /home/jnelson/src/wasi-libc/sysroot/lib/wasm32-wasi/libc.a
  ```

- Don't print all header files removed when installing include files
  There are several dozen of these, and the exact files being removed aren't super useful to know
  when building. Instead, print `RM MUSL_OMIT_HEADERS`, which gives enough info to know where in the makefile to look for the actual files.

### CODE REVIEW

**Comment by jyn514** [comment]
To give an idea of how much noise this omits, here's a full build before this change:
```
$ make >output-noisy.txt 2>&1
$ wc -c output-noisy.txt 
773850 output-noisy.txt
$ wc -l output-noisy.txt 
906 output-noisy.txt
```
and after:
```
$ make >output.txt 2>&1
$ wc -c output.txt 
39540 output.txt
$ wc -l output.txt 
858 output.txt
```

**Comment by sbc100** [comment]
Is there any harm in outputting all that information/noise though?    The primay place this Makefile gets run is probably github CI and it seems reasonable to include the full command lines to easy debugging, no?

At the very least isn't it important to see the full command line of a command that fails?   I think this is why cmake builds makefiles that have some kind of VERBOSE option, even then its turns off by default.  ninja is very nice in that it can be quite as long as command succeeds but then echos the full command line if it fails.

Anyway, I'm curious why you care about verbosity here?

**Comment by jyn514** [comment]
> Is there any harm in outputting all that information/noise though? The primay place this Makefile gets run is probably github CI and it seems reasonable to include the full command lines to easy debugging, no?

We (Cloudflare) use wasi in our Workers runtime, so this output also shows up in our own CI. A recent logfile from that was 4172310 characters long; so a good 5% of that is coming *just* from wasi and nothing else. Since wasi never fails in our CI, all that output is basically just noise.

> At the very least isn't it important to see the full command line of a command that fails? I think this is why cmake builds makefiles that have some kind of VERBOSE option, even then its turns off by default. ninja is very nice in that it can be quite as long as command succeeds but then echos the full command line if it fails.

I can add a VERBOSE option if you think that's helpful :) I don't know how to get make to output the build command only if it failed, though. (I agree ninja has a much nicer UI than make, but the syntax isn't compatible IIRC.)

**Comment by jyn514** [comment]
> The primay place this Makefile gets run is probably github CI

I'm kind of curious - is no one else building wasi-libc locally? It seems strange that you'd expect this to be a CI-only thing.

**Comment by sbc100** [comment]
> > Is there any harm in outputting all that information/noise though? The primay place this Makefile gets run is probably github CI and it seems reasonable to include the full command lines to easy debugging, no?
> 
> We (Cloudflare) use wasi in our Workers runtime, so this output also shows up in our own CI. A recent logfile from that was 4172310 characters long; so a good 5% of that is coming _just_ from wasi and nothing else. Since wasi never fails in our CI, all that output is basically just noise.

I see.  How about just running `make > /dev/null` ?   Or `make > buildlog.txt`?   You will still get any errors on stderr which is the most important thing.   Of course, you won't see the failing command, but that is not different to this patch which also hides the command line.

**Comment by sbc100** [comment]
> > The primay place this Makefile gets run is probably github CI
> 
> I'm kind of curious - is no one else building wasi-libc locally? It seems strange that you'd expect this to be a CI-only thing.

Sorry, yes we do run this locally in development yes.   But the github UI is where I often end up looking logs (and having the full commands is quite useful there for debugging multi-platform issues).

I'm not totally against this patch.  If you want to land make it optional and perhaps even opt in (make QUIET=1) I think that would OK.

**Pull request closed without merging**
