### PR TITLE
Update CI to use latest Clang version

### PR DESCRIPTION
**Pull request by abrown**
Looking at the LLVM [releases], this change attempts an update to v16.0.6.

[releases]: https://github.com/llvm/llvm-project/releases

### CODE REVIEW

**Comment by sbc100** [comment]
Any particular reason you care about this?

**Comment by abrown** [comment]
> Any particular reason you care about this?

No, was just wondering. Seems like it won't be easy, though...

**Review by sbc100 — APPROVED** [review]
Why didn't 16 work?

**Comment by abrown** [comment]
> Why didn't 16 work?

Later versions of LLVM have a new naming structure; and the v16 releases don't include the necessary `x86_64-apple-darwin` files.

**Review by yamt — CHANGES_REQUESTED** [review]
https://github.com/WebAssembly/wasi-libc/pull/394 includes more complete changes.

**Comment by abrown** [comment]
Closed by #394.

**Pull request closed without merging**
