### PR TITLE
build: update WASI and partially regenerate `api.h`

### PR DESCRIPTION
**Pull request by rvolosatovs**
Updated the WASI dependency and partially regenerated `api.h` using existing tooling.

Most notably this is required for `sock_accept` support added in https://github.com/WebAssembly/WASI/pull/458

### CODE REVIEW

**Review by sbc100 — APPROVED** [review]

**Comment by rvolosatovs** [comment]
> Would you be able to rebase this on main? I expect that will fix the CI failure here.

Sure! I'll see if I have time tomorrow, otherwise will address it next week

**Comment by rvolosatovs** [comment]
@sunfishcode done, please take a look

The commit applied cleanly and it seems that there were no significant changes in the area

**Comment by rvolosatovs** [comment]
Filed a follow-up #284

**Comment by npmccallum** [comment]
@sunfishcode Could this be merged? We'd like to move on to accept support.

**Comment by sunfishcode** [comment]
Yes, looks good.

**Pull request merged**
