### PR TITLE
Add build flag to select malloc implementation

### PR DESCRIPTION
**Pull request by aykevl**
Add a build flag MALLOC_IMPL that can be set to dlmalloc or none (defaulting to dlmalloc) which controls the malloc implementation to use. The dlmalloc option is the same as before, but selecting none removes dlmalloc from the libc build.

This flag replaces the BUILD_DLMALLOC flag, which never worked and thus can be removed without breaking any builds. By switching to MALLOC_IMPL, there is a clear path towards a different heap implementation, such as mimalloc.

See https://github.com/WebAssembly/wasi-libc/issues/94 and https://github.com/WebAssembly/wasi-libc/issues/244 for context.

I don't really like the long grep lines, if somebody knows of a better way to remove these symbols I'd like to fix it.

### CODE REVIEW

**Comment by sbc100** [comment]
What didn't work about `BUILD_DLMALLOC` exactly?  

Why not just fix that option for now, given that we don't have any other malloc options yet? 

If we are going to include options, I wonder if we should include musl's own malloc as a possible option?  Maybe there is no reason to do that though..

I wonder if we can just skip the symbol tests if malloc is not desired, or if think its valuable we could have different `expected.txt` file for each libc variant that we support?

**Comment by sunfishcode** [comment]
Skipping the symbol test if malloc is not desired sounds reasonable to me here.

**Comment by aykevl** [comment]
> What didn't work about `BUILD_DLMALLOC` exactly?

The new `MALLOC_IMPL` is just a more flexible replacement for `BUILD_DLMALLOC` so it would require the exact same changes as I needed to do for `BUILD_DLMALLOC`. You can see this in the diff. Presumably the symbol check is the reason why this flag was disabled.

> Why not just fix that option for now, given that we don't have any other malloc options yet?

To be forward compatible with other allocators. Yes, I could most certainly make this PR in a way that it fixes `BUILD_DLMALLOC` (which is currently defunct and presumably unused for that reason) but then people (like me) might start depending on the flag and require a change once more allocators are added.

If desired I can certainly change this PR to use the flag `BUILD_DLMALLOC` instead of `MALLOC_IMPL` but explicitly providing 'none' or 'dlmalloc' seems more flexible to me.

> If we are going to include options, I wonder if we should include musl's own malloc as a possible option? Maybe there is no reason to do that though..

Sure, that might be possible (I didn't look at the musl allocator and whether it can run on wasm). But it seems better to do that separately, when someone actually needs it.

> I wonder if we can just skip the symbol tests if malloc is not desired, or if think its valuable we could have different `expected.txt` file for each libc variant that we support?

Sure, that step can be skipped in that case. A different defined-symbols.txt and undefined-symbols.txt for each malloc seems like a bad idea to me for maintenance and in case another such flag will be added in the future.

I'll investigate skipping this step.

**Comment by aykevl** [comment]
Updated, skipping the metadata verification step when a non-standard heap allocator is used.

**Comment by sunfishcode** [comment]
Thanks! This looks good.

**Pull request merged**
